language: node_js
node_js:
 - "0.12"
after_success:
 - npm install istanbul
 - istanbul cover ./node_modules/mocha/bin/_mocha  ./test/
 - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
